### ISSUE TITLE
Chapter 2 exercises file is not rendering correctly 

### ISSUE THREAD

**Issue by LRhoads2025** [jermwatt/mlrefined#27]
When opening the jupyter file ,it does not render in the github viewer correctly. It's very difficult to read.

**Comment by neonwatty** [comment]
Thanks for the heads up!  All fixed - [see here](https://github.com/jermwatt/machine_learning_refined/blob/gh-pages/mlrefined_exercises/ed_2/chapter_2/chapter_2_exercises.ipynb).
