### ISSUE TITLE
downloading the repository in the form of zip

### ISSUE THREAD

**Issue by mehdi-moha** [jermwatt/mlrefined#30]
Hello
After today's update, the folder "https://github.com/jermwatt/machine_learning_refined/tree/gh-pages/sample_chapters" files are not downloaded correctly by downloading the repository in the form of zip.

**Comment by neonwatty** [comment]
That's weird - I'm not sure what the issue is at present.  I can still 

- download them directly from the browser 
- get them via cloning the repo

I'll look into the issue further and get back when I've figured out whats going wrong with the zip.

**Comment by mehdi-moha** [comment]
Thank you for your kindness
