### ISSUE TITLE
NameError: name 'animator' is not defined

### ISSUE THREAD

**Issue by Atcold** [jermwatt/mlrefined#33]
Cell [16] of 6_2_Cross_entropy notebook tries to use `animator`, which is never defined.

**Comment by neonwatty** [comment]
Thanks!  Fixed and updated.

**Comment by Atcold** [comment]
Where is the closing commit and reference to this PR?
I've also emailed you. Do you mind getting back to me?

**Comment by neonwatty** [comment]
Apologies - here is [the commit](https://github.com/neonwatty/machine_learning_refined/commit/e8054c33da2729fbfe0eb55171473ca010f26e86) - submitted directly to main.

Re-opened for future discussion.

**Comment by Atcold** [comment]
Oh, thanks! All good.
